/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.JsonApiBodyRequest;
import io.swagger.model.JsonApiBodyResponseErrors;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-25T19:33:57.780Z")

@Api(value = "listar", description = "the listar API")
public interface ListarApi {

    @ApiOperation(value = "buscar persona por estado", nickname = "listarEstadoEstadoGet", notes = "retorna las personas deacuerdo a roles", response = JsonApiBodyRequest.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "listado de roles", response = JsonApiBodyRequest.class),
        @ApiResponse(code = 404, message = "estado no encontrado", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/listar/estado/{estado}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<JsonApiBodyRequest> listarEstadoEstadoGet(@ApiParam(value = "rol de personas a retornar",required=true) @PathVariable("estado") String estado);


    @ApiOperation(value = "Retorna todos los usuarios", nickname = "listarGet", notes = "Retorna todos los usuarios", response = JsonApiBodyRequest.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "persona(s) encontradas", response = JsonApiBodyRequest.class),
        @ApiResponse(code = 404, message = "no encontrado", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/listar",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<?> listarGet();


    @ApiOperation(value = "buscar persona por id", nickname = "listarIdGet", notes = "retorna una persona por id", response = JsonApiBodyRequest.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = JsonApiBodyRequest.class),
        @ApiResponse(code = 404, message = "rol no encontrado", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/listar/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<?> listarIdGet(@ApiParam(value = "ID de la persona",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "buscar persona por rol", nickname = "listarRolRolGet", notes = "retorna las personas deacuerdo a roles", response = JsonApiBodyRequest.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "listado de roles", response = JsonApiBodyRequest.class),
        @ApiResponse(code = 404, message = "rol no encontrado", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/listar/rol/{rol}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<?> listarRolRolGet(@ApiParam(value = "rol de personas a retornar",required=true) @PathVariable("rol") String rol);

}
